### ISSUE TITLE
New script for "jenkins_centos/install-jenkins-centos.sh"

### ISSUE THREAD

**Issue by Marella139** [sharadchhetri/scripts#3]
Please update the content of the _jenkins_centos/install-jenkins-centos.sh_ script because the default one is not up to date.

Down below is the modified version of the script:

```
#/bin/bash
#
# Install jfrog on CentOS 8
# Tutorial URL: https://sharadchhetri.com/2020/06/13/how-to-install-jfrog-artifactory-on-centos-8/

# Disable the SELINUX on CentOS 8
# set temporary permissive selinux mode. reboot not require
sudo setenforce 0
# In next reboot,the below line will help to set disable selinux permanently.
sudo sed -i s/^SELINUX=.*$/SELINUX=disabled/ /etc/selinux/config

# download jfrog repo and directly keep in /etc/yum.repos.d dir
sudo wget -O /etc/yum.repos.d/artifactory-pro.rpm "https://releases.jfrog.io/artifactory/artifactory-pro-rpms/jfrog-artifactory-pro/jfrog-artifactory-pro-[RELEASE].rpm"

# install jfrog-artifactory-oss (open source)
sudo yum install -y /etc/yum.repos.d/artifactory-pro.rpm

# yaml files are indent sensitive. So do not remove spaces while copying. Keep as it is.
# creating system.yaml
cat <<EOF >system.yaml
configVersion: 1
shared:
    extraJavaOpts: "-server -Xms512m -Xmx2g -Xss256k -XX:+UseG1GC"
    security:
    node:
    database:
EOF

# copying above created system.yaml and replacing by original one 
sudo cp -brvf system.yaml /var/opt/jfrog/artifactory/etc/system.yaml

# enable artifactoyr.service as well as start the service at a same time
sudo systemctl enable --now artifactory

# Now open web browser - http://<jfrog-ip-or-fqdn>:8081 and do the post setup of jfrog.
```
